before_install:
  - npm install
language: java
sudo: false
cache:
  directories:
  - $HOME/.gradle
jdk:
  - oraclejdk8
env:
  matrix:
    - CI_MODE=Released
    - CI_MODE=Nightly

# Make released optional
matrix:
  fast_finish: true
  allow_failures:
    - env: "CI_MODE=Released"

